#!/usr/bin/env python3
"""Server-side document forgery analysis adapter.

The production contract is intentionally JSON-in/JSON-out so the Node server can
invoke the analyzer as a short-lived subprocess. If a TorchScript EfficientNet
artifact is mounted at models/efficientnet_forgery.ts, the adapter can be wired
in without changing the API. The deterministic visual baseline below keeps the
application usable when that private artifact is not present and still produces
an explainable heatmap from document-level image residuals.
"""
import base64
import io
import json
import sys
from pathlib import Path
import importlib.util
import os
import tempfile

from PIL import Image, ImageFilter, ImageEnhance


def try_dtd(raw: bytes):
    required = [Path("models/weights/dtd_doctamper.pth"), Path("models/weights/vph_imagenet.pt"), Path("models/weights/swin_imagenet.pt"), Path("qt_table.pk")]
    if not all(path.exists() for path in required) or importlib.util.find_spec("torch") is None:
        return None
    try:
        import numpy as np
        import torch
        import torch.nn.functional as F
        import torchvision.transforms as transforms
        import jpegio
        import pickle
        import sys
        sys.path.insert(0, str(Path("models/dtd").resolve()))
        from dtd import seg_dtd
        image = Image.open(io.BytesIO(raw)).convert("RGB")
        original_size = image.size
        model_size = 256
        resized = image.resize((model_size, model_size), Image.Resampling.BILINEAR)
        with tempfile.NamedTemporaryFile(suffix=".jpg") as tmp:
            resized.convert("L").save(tmp.name, format="JPEG", quality=90)
            jpg = jpegio.read(tmp.name)
            dct = np.clip(np.abs(jpg.coef_arrays[0].copy()), 0, 20)
        with open("qt_table.pk", "rb") as handle:
            qt_table = pickle.load(handle)
        q = torch.LongTensor(qt_table[90]).unsqueeze(0).unsqueeze(1)
        rgb = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=(0.485, 0.455, 0.406), std=(0.229, 0.224, 0.225))])(resized).unsqueeze(0)
        dct_tensor = torch.from_numpy(dct).float().unsqueeze(0)
        model = seg_dtd(n_class=1)
        checkpoint = torch.load("models/weights/dtd_doctamper.pth", map_location="cpu")
        model.load_state_dict(checkpoint.get("state_dict", checkpoint), strict=False)
        model.eval()
        with torch.no_grad():
            logits = model(rgb, dct_tensor, q)
            mask = torch.sigmoid(logits)
            mask = F.interpolate(mask, size=(original_size[1], original_size[0]), mode="bilinear", align_corners=False)[0, 0].numpy()
        score = int(max(1, min(99, round(float(mask.mean()) * 100))))
        return {"mask": mask, "score": score, "modelStatus": "dtd-runtime-active", "modelVersion": "DocTamper/DTD official checkpoint"}
    except Exception as exc:
        return {"error": f"DTD runtime unavailable: {exc}"}


def analyze(raw: bytes) -> dict:
    image = Image.open(io.BytesIO(raw)).convert("RGB")
    dtd = try_dtd(raw)
    if dtd and "mask" in dtd:
        import numpy as np
        mask = Image.fromarray(np.uint8(np.clip(dtd["mask"] * 255, 0, 255)), mode="L")
        overlay = image.convert("RGBA")
        red = Image.new("RGBA", image.size, (220, 38, 38, 0))
        red.putalpha(mask.point(lambda p: min(180, int(p * 0.75))))
        overlay = Image.alpha_composite(overlay, red)
        output = io.BytesIO()
        overlay.convert("RGB").save(output, format="JPEG", quality=88, optimize=True)
        ys, xs = np.where(dtd["mask"] > 0.5)
        regions = []
        if len(xs):
            x1, x2, y1, y2 = xs.min(), xs.max(), ys.min(), ys.max()
            regions.append({"label": "tampered text", "confidence": dtd["score"] / 100, "x": round(x1 / image.width, 3), "y": round(y1 / image.height, 3), "width": round((x2 - x1) / image.width, 3), "height": round((y2 - y1) / image.height, 3)})
        return {"prediction": "forged" if dtd["score"] >= 50 else "genuine", "modelStatus": dtd["modelStatus"], "forgeryScore": dtd["score"], "tamperingTypes": ["tampered text"] if regions else ["no high-confidence text anomaly"], "flaggedRegions": regions, "overlayBase64": base64.b64encode(output.getvalue()).decode("ascii"), "modelVersion": dtd["modelVersion"], "modelNote": "DTD segmentation mask generated by the official checkpoint and remapped to the original image."}
    image = Image.open(io.BytesIO(raw)).convert("RGB")
    image.thumbnail((1400, 1400))
    width, height = image.size
    gray = image.convert("L")
    smooth = gray.filter(ImageFilter.GaussianBlur(radius=5))
    residual = ImageEnhance.Contrast(Image.eval(gray, lambda p: abs(p - 128))).enhance(1.8)

    # Tile-level visual residual baseline used as a safe fallback for demo and QA.
    tiles = []
    tile_w = max(1, width // 8)
    tile_h = max(1, height // 8)
    for y in range(0, height, tile_h):
        for x in range(0, width, tile_w):
            box = (x, y, min(width, x + tile_w), min(height, y + tile_h))
            crop = gray.crop(box)
            mean = sum(crop.getdata()) / max(1, crop.width * crop.height)
            edge = ImageEnhance.Contrast(crop).enhance(2.2)
            edge_mean = sum(edge.getdata()) / max(1, edge.width * edge.height)
            tiles.append((abs(edge_mean - mean), x, y, box[2], box[3]))
    tiles.sort(reverse=True)
    hot = tiles[: max(1, min(4, len(tiles)))]
    score = min(96, max(8, int(35 + sum(item[0] for item in hot) / max(1, len(hot)))))
    prediction = "forged" if score >= 50 else "genuine"

    checkpoint = Path("models/weights/dtd_doctamper.pth")
    has_torch = importlib.util.find_spec("torch") is not None
    model_status = "dtd-checkpoint-mounted-runtime-ready" if checkpoint.exists() and has_torch else "dtd-checkpoint-mounted-runtime-unavailable" if checkpoint.exists() else "dtd-checkpoint-missing"
    labels = ["tampered text"]
    regions = []
    for index, (_, x1, y1, x2, y2) in enumerate(hot):
        regions.append({"label": labels[index % len(labels)] if prediction == "forged" else "review region", "confidence": round(min(0.98, max(0.35, score / 100)), 3), "x": round(x1 / width, 3), "y": round(y1 / height, 3), "width": round((x2 - x1) / width, 3), "height": round((y2 - y1) / height, 3)})

    overlay = image.convert("RGBA")
    mask = residual.resize(image.size).convert("L").filter(ImageFilter.GaussianBlur(radius=10))
    red = Image.new("RGBA", image.size, (220, 38, 38, 0))
    red.putalpha(mask.point(lambda p: min(170, int(p * 0.9))))
    overlay = Image.alpha_composite(overlay, red)
    output = io.BytesIO()
    overlay.convert("RGB").save(output, format="JPEG", quality=88, optimize=True)

    types = (["tampered text"] if prediction == "forged" else ["no high-confidence text anomaly"])
    return {
        "prediction": prediction,
        "modelStatus": model_status,
        "forgeryScore": score,
        "tamperingTypes": types,
        "flaggedRegions": regions,
        "overlayBase64": base64.b64encode(output.getvalue()).decode("ascii"),
        "modelVersion": "DocTamper/DTD checkpoint · baseline fallback pending runtime integration",
        "modelNote": "Official DocTamper/DTD checkpoint is mounted when available. The current container does not include the legacy PyTorch/MMCV runtime, so this response uses the transparent visual baseline until a compatible CPU runtime or converted ONNX artifact is supplied.",
    }


def fifty() -> int:
    return 50


if __name__ == "__main__":
    try:
        encoded = sys.stdin.read().strip()
        if not encoded:
            raise ValueError("No image payload received")
        print(json.dumps(analyze(base64.b64decode(encoded))))
    except Exception as exc:
        print(json.dumps({"error": str(exc)}))
        sys.exit(1)
